services:
  database:
    image: mysql:8.0
    ports:
      - ${DB_FORWARD_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
      - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jsonapi
      - MYSQL_USER=jsonapi
      - MYSQL_PASSWORD=jsonapi
  mailer:
    image: mailhog/mailhog:latest
    environment:
      - MH_STORAGE=maildir
    ports:
      - '${MAILHOG_PORT:-8025}:8025'

volumes:
  db-data: